### ISSUE TITLE
ParsePush.SubscribeAsync() & SaveAsync() Keep throwing System.AggregateException all the time on Windows 10 UWP

### ISSUE THREAD

**Issue by SamAlbuga** [ParsePlatform/Parse-SDK-dotNET#100]
ParsePush.SubscribeAsync() & SaveAsync() Keep throwing System.AggregateException all the time on Windows 10 UWP. Also The framework doesn't even register installations.

Here the stack trace:
```
Exception thrown: 'System.AggregateException' in mscorlib.ni.dll
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Parse.PlatformHooks.get_AppName()
   at Parse.ParseInstallation.SaveAsync(Task toAwait, CancellationToken cancellationToken)
   at Parse.ParseObject.<>c__DisplayClass41.<SaveAsync>b__40(Task toAwait)
   at Parse.Internal.TaskQueue.Enqueue[T](Func`2 taskStart, CancellationToken cancellationToken)
   at Parse.ParseObject.SaveAsync(CancellationToken cancellationToken)
   at Parse.ParseObject.SaveAsync()
   at MyApp.MainPage.<Page_Loaded>d__1.MoveNext()
```

Help! I cannot get it working and I didn't see similar cases.
**Note that I'm using Parse from NuGet**

**Comment by SamAlbuga** [comment]
Solved by @Julien-Mialon in pull request #91  It was caused by by AppName getting trying to access AppManifest using an old Xml schema.
